
CREATE PROCEDURE LV_IMPRIMI_VENDA_CLIENTE_P1
AS
BEGIN
SELECT C.ID_CLIENTE AS CODIGO,C.NM_CLIENTE AS NOME, C.CPF_CLIENTE AS CPF, C.RG_CLIENTE AS RG FROM CLIENTE C
INNER JOIN VENDA V ON V.ID_CLIENTE = C.ID_CLIENTE
INNER JOIN LPARAM L ON L.LVRPARAM = V.ID_VENDA
WHERE L.LMNPARAM='IMPVND'
END
/*------------------------------------------------------------------------------------------------------------------*/
CREATE PROCEDURE LV_IMPRIMI_VENDA_CLIENTE_P2
AS
BEGIN
SELECT C.ENDERECO_CLIENTE AS ENDERECO,C.NUMERO_ENDERECO_CLIENTE AS NUMERO,
C.BAIRRO_ENDERECO_CLIENTE AS BAIRRO,C.CEP_ENDERECO_CLIENTE AS CEP, U.DS_UF AS UF,
I.DS_CIDADE AS CIDADE FROM CLIENTE C
INNER JOIN VENDA V ON V.ID_CLIENTE = C.ID_CLIENTE
INNER JOIN UF U ON U.ID_UF = C.ID_UF
INNER JOIN CIDADE I ON I.ID_CIDADE = C.ID_CIDADE
INNER JOIN LPARAM L ON L.LVRPARAM = V.ID_VENDA
WHERE L.LMNPARAM='IMPVND'
END

CREATE PROCEDURE LV_IMPRIMI_VENDA_CLIENTE_P3
AS
BEGIN
SELECT I.ID_PRODUTO AS CODIGO,P.NM_PRODUTO AS PRODUTO,I.VALOR_PRODUTO,
I.QT_PRODUTO AS QUANTIDADE, I.VALOR_TOTAL AS TOTAL FROM VENDA V 
INNER JOIN VENDA_ITENS I ON V.ID_VENDA = I.ID_VENDA
INNER JOIN PRODUTO P ON P.ID_PRODUTO = I.ID_PRODUTO
INNER JOIN LPARAM L ON L.LVRPARAM = V.ID_VENDA
WHERE L.LMNPARAM='IMPVND'
END

CREATE PROCEDURE LV_IMPRIMI_VENDA_CLIENTE_P4
AS
BEGIN
SELECT V.VL_FINAL_VENDA FROM VENDA V 
INNER JOIN LPARAM L ON L.LVRPARAM = V.ID_VENDA
WHERE L.LMNPARAM='IMPVND'
END
SELECT * FROM VENDA_ITENS