
CREATE PROCEDURE LV_INSERIR_CONT_V1
@CTPCONT INT,
@CDTLANC SMALLDATETIME,
@CCODORI INT,
@CVLRCNT DECIMAL(9,2),
@CDTPAG SMALLDATETIME,
@CDTVCTO SMALLDATETIME,
@COBS VARCHAR(250),
@ID_OUT INT OUTPUT
AS
BEGIN
INSERT INTO CNTPGRC
(CTPCONT,CDTLANC,CCODORI,CVLRCNT,CDTPAG,CDTVCTO,COBS)
VALUES
(@CTPCONT, @CDTLANC,@CCODORI,@CVLRCNT,@CDTPAG,@CDTVCTO,@COBS)
SET @ID_OUT = (SELECT SCOPE_IDENTITY())
RETURN @ID_OUT
END