CREATE PROCEDURE USP_OBTER_STATUS_PET
@ID_PET INT
AS
	SELECT P.ID_ESPECIE, E.DS_ESPECIE, P.ID_RACA, R.DS_RACA, P.ID_PORTE, A.DS_PORTE 
	FROM PET P
	INNER JOIN ESPECIE E ON E.ID_ESPECIE= P.ID_ESPECIE
	INNER JOIN RACA R ON R.ID_RACA = P.ID_RACA
	INNER JOIN PORTE A ON A.ID_PORTE = P.ID_PORTE
	WHERE P.ID_PET = @ID_PET
	
	
