CREATE TABLE CNTPGRC
(CCODCONT INT PRIMARY KEY IDENTITY,
CTPCONT INT NOT NULL,
CDTLANC SMALLDATETIME NOT NULL,
CCODORI INT NOT NULL,
CVLRCNT DECIMAL(9,2) NOT NULL,
CDTPAG SMALLDATETIME NOT NULL,
CDTVCTO SMALLDATETIME,
COBS VARCHAR(250)
)