CREATE PROCEDURE USP_VENDA_DIA
AS
SELECT V.ID_PLANOPAGAMENTO, P.DS_PLANO, SUM(V.VL_FINAL_PRODUTOs) FROM VENDA V
INNER JOIN DORMA P ON P.ID_PLANOPAGAMENTO = V.ID_PLANOPAGAMENTO
GROUP BY V.ID_PLANOPAGAMENTO, P.DS_PLANO