USE [LIVECOMMERCE]
GO

/****** Object:  StoredProcedure [dbo].[LV_VENDA_FORMA_PAGAMENTO_DIA]    Script Date: 30/03/2020 14:45:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[LV_VENDA_FORMA_PAGAMENTO_DIA]
AS
SELECT P.DS_FORMAPAGAMENTO,COUNT(V.ID_VENDA) AS QTD_VENDA, SUM(V.VL_FINAL_VENDA) AS VLR_VENDA
FROM VENDA V 
INNER JOIN FORMA_DE_PAGAMENTO P ON V.ID_FORMAPAGAMENTO = P.ID_FORMAPAGAMENTO
WHERE V.DT_VENDA = CONVERT(DATE,GETDATE()) AND V.STATUS ='FINALIZADA'
GROUP BY V.ID_FORMAPAGAMENTO, P.DS_FORMAPAGAMENTO

GO


