CREATE PROCEDURE LV_CONTA_PAGAR_RECEBER_CONFIRMA_PAGAMENTO_CANCELAMENTO
@ID INT,
@DATAPAGAMENTO SMALLDATETIME,
@STATUS VARCHAR(1)
AS
DECLARE 
@NRDOC VARCHAR(20),
@NRPARC VARCHAR(5)
SELECT @NRDOC=CSNRDOC, @NRPARC=CSNRPARC FROM CNTPGRC WHERE CCODCONT=@ID
BEGIN
	--Realizando a baixa na tabela de contas a pagar e receber
	UPDATE CNTPGRC SET CDTPAG=@DATAPAGAMENTO, CSTATUS=@STATUS WHERE CCODCONT=@ID

IF((SELECT CSNRPARC FROM CNTPGRC WHERE CCODCONT=@ID) <> '')
	--Realizando a baixa na tela de parcelas
	UPDATE PARCELA SET PADTPAG=@DATAPAGAMENTO WHERE PANRPARC=@NRPARC AND PAIDVEND=@NRDOC
END