CREATE PROCEDURE LV_CONTAPAGAR_RECEBER_TIPO_V1
@TIPO VARCHAR(10)
AS
BEGIN
	IF @TIPO = 1
	
		SELECT V.CCODCONT [Cód],(SELECT TOP 1 L.LTDSC FROM LTGEN WHERE L.LTCOD=@TIPO) [Tipo],C.NOME_FANTASIA [Nome],V.CDTLANC [Dt. Lanç.],
		v.CVLRCNT [Valor], v.CDTVCTO [Dt. Vencimento],v.CDTPAG [Dt. Pagamento], v.COBS [Observação]
		FROM CNTPGRC V 
		INNER JOIN FORNECEDOR C ON C.ID_FORNECEDOR = V.CCODORI
		INNER JOIN LTGEN L ON L.LTCOD = V.CTPCONT
		WHERE V.CTPCONT =@TIPO AND L.LTTP =1 AND V.CSTATUS ='A'
	ELSE
		SELECT V.CCODCONT [Cód],(SELECT TOP 1 L.LTDSC FROM LTGEN WHERE L.LTCOD=@TIPO) [Tipo],C.NM_CLIENTE [Nome],V.CDTLANC [Dt. Lanç.],
		v.CVLRCNT [Valor], v.CDTVCTO [Dt. Vencimento],v.CDTPAG [Dt. Pagamento], v.COBS [Observação]
		FROM CNTPGRC V 
		INNER JOIN CLIENTE C ON C.ID_CLIENTE = V.CCODORI
		INNER JOIN LTGEN L ON L.LTCOD = V.CTPCONT
		WHERE V.CTPCONT =@TIPO AND L.LTTP =1 AND V.CSTATUS ='A'
END