CREATE PROCEDURE LV_CONTA_PAGAR_RECEBER_CONFIRMA_PAGAMENTO_CANCELAMENTO
@ID INT,
@DATAPAGAMENTO SMALLDATETIME,
@STATUS VARCHAR(1)
AS
BEGIN
UPDATE CNTPGRC SET CDTPAG=@DATAPAGAMENTO, CSTATUS=@STATUS WHERE CCODCONT=@ID
END