
CREATE PROCEDURE LV_RELATORIO_CONTAS_RECEBIDAS_V1
@DATAINICIAL DATE,
@DATAFINAL DATE
AS
BEGIN
		SELECT V.CCODCONT [CÓD],C.NM_CLIENTE [NOME],V.CDTLANC [DT. LANÇ.],
		V.CVLRCNT [VALOR], V.CDTVCTO [DT. VENCIMENTO],V.CDTPAG [DT. PAGAMENTO], V.COBS [OBSERVAÇÃO]
		FROM CNTPGRC V 
		INNER JOIN CLIENTE C ON C.ID_CLIENTE = V.CCODORI
		INNER JOIN LTGEN L ON L.LTCOD = V.CTPCONT
		WHERE V.CTPCONT =2 
		AND V.CSTATUS ='P'
		AND V.CDTPAG  BETWEEN @DATAINICIAL AND @DATAFINAL
END