CREATE TABLE CNTPGRC
(CCODCONT INT PRIMARY KEY IDENTITY,
CTPCONT INT NOT NULL,
CDTLANC SMALLDATETIME NOT NULL,
CCODORI INT NOT NULL,
CVLRCNT DECIMAL(9,2) NOT NULL,
CDTPAG SMALLDATETIME NULL,
CDTVCTO SMALLDATETIME NOT NULL,
COBS VARCHAR(250),
CSTATUS CHAR(1) NOT NULL DEFAULT 'A'
)