GO
USE MASTER

GO
DROP DATABASE PETS201802


GO
CREATE DATABASE PETS201802

GO
USE PETS201802;

GO
CREATE TABLE SITUACAO
(ID_SITUACAO INT NOT NULL IDENTITY PRIMARY KEY,
 DS_SITUACAO VARCHAR (10) );
 
GO
CREATE TABLE ESPECIE
	(ID_ESPECIE INT NOT NULL PRIMARY KEY IDENTITY,
	 DS_ESPECIE VARCHAR (50) NOT NULL)

CREATE TABLE PORTE
	(ID_PORTE INT NOT NULL PRIMARY KEY IDENTITY,
	 DS_PORTE VARCHAR (50) NOT NULL)


CREATE TABLE SEXO
	(ID_SEXO INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	 DS_SEXO VARCHAR (10) NOT NULL)

CREATE TABLE TIPO_PRODUTO
(ID_TIPO INT NOT NULL PRIMARY KEY IDENTITY,
 DS_TIPO VARCHAR (30))



CREATE TABLE FORMA_DE_PAGAMENTO
	(ID_FORMAPAGAMENTO INT NOT NULL IDENTITY PRIMARY KEY,
	 DS_FORMAPAGAMENTO VARCHAR (20) NOT NULL)

GO
CREATE TABLE UNIDADE_MEDIDA
(ID_UNIDADE_MEDIDA INT PRIMARY KEY IDENTITY NOT NULL,
 DS_UNIDADE_MEDIDA VARCHAR (5) NOT NULL)



GO
CREATE TABLE CATEGORIA_PRODUTO
(ID_CATEGORIA_PRODUTO INT PRIMARY KEY IDENTITY NOT NULL,
 DS_CATEGORIA_PRODUTO VARCHAR(10) NOT NULL)


CREATE TABLE USUARIO
	(ID_USUARIO INT NOT NULL PRIMARY KEY IDENTITY,
	 NM_USUARIO VARCHAR (10) NOT NULL,
	 DS_USUARIO VARCHAR (10),
	 SENHA_USUARIO VARCHAR (50)NOT NULL)

CREATE TABLE UF
(ID_UF INT NOT NULL PRIMARY KEY IDENTITY,
 DS_UF VARCHAR(2) NOT NULL);

CREATE TABLE RACA
	(ID_RACA INT NOT NULL PRIMARY KEY IDENTITY,
	 DS_RACA VARCHAR (50) NOT NULL,
	 ID_ESPECIE INT  CONSTRAINT ESPECIE_ANIMAL_FK FOREIGN KEY (ID_ESPECIE) REFERENCES ESPECIE)

CREATE TABLE PLANO_DE_PAGAMENTO
	(ID_PLANOPAGAMENTO INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	 DS_PLANOPAGAMENTO VARCHAR (20) NOT NULL ,
	 VL_MINIMO FLOAT NOT NULL,
	 QT_PARCELAS INT NOT NULL,
	 ID_FORMAPAGAMENTO INT NOT NULL CONSTRAINT PLANO_PAGAMENTO_FORMA_PAGMENTO_FK FOREIGN KEY (ID_FORMAPAGAMENTO) REFERENCES FORMA_DE_PAGAMENTO )

CREATE TABLE CIDADE
(ID_CIDADE INT NOT NULL IDENTITY PRIMARY KEY,
 ID_UF INT CONSTRAINT UF_CIADE_FK FOREIGN KEY (ID_UF) REFERENCES UF,
 DS_CIDADE VARCHAR (50)NOT NULL)

CREATE TABLE CLIENTE 
	(ID_CLIENTE INT NOT NULL IDENTITY PRIMARY KEY,
	 DATA_CADASTRO DATE,
	 PESSOA VARCHAR (10) NOT NULL,
	 NM_CLIENTE VARCHAR (35) NOT NULL ,
	 CPF_CLIENTE VARCHAR (11),
	 DT_NASCIMENTO_CLIENTE DATE NOT NULL,
	 ENDERECO_CLIENTE VARCHAR (50),
	 NUMERO_ENDERECO_CLIENTE INT,
	 BAIRRO_ENDERECO_CLIENTE VARCHAR (30),
	 CEP_ENDERECO_CLIENTE VARCHAR (9),	 
	 ID_UF INT CONSTRAINT UF_CLIENTE_FK FOREIGN KEY (ID_UF) REFERENCES UF,
	 ID_SITUACAO INT CONSTRAINT SITUACAO_CLIENTE_FK FOREIGN KEY (ID_SITUACAO) REFERENCES SITUACAO,
	 ID_CIDADE INT CONSTRAINT CIDADE_CLIENTE_FK FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE)

CREATE TABLE FUNCIONARIO
	(ID_FUNCIONARIO INT NOT NULL PRIMARY KEY IDENTITY,
	 NM_FUNCIONARIO VARCHAR (50) NOT NULL,
	 CPF_FUNCIONARIO VARCHAR (20) NOT NULL,
	 END_FUNCIONARIO VARCHAR (50) NOT NULL,
	 TEL_FUNCIONARIO VARCHAR (15) NOT NULL, 
	 EMAIL_FUNCIONARIO VARCHAR (30) NOT NULL,
	 CM_FUNCIONARIO FLOAT ,
	 DT_NASCIMENTO_FUNCIONARIO DATE,
	 BAIRRO_ENDERECO_FUNCIONARIO VARCHAR (25) NOT NULL,
	 NUMERO_ENDERECO_FUNCIONARIO INT,	 
	 CIDADE_ENDERECO_FUNCIONARIO VARCHAR(30) NOT NULL,
	 SALARIO_BASE_FUNCIONARIO FLOAT,
	 ID_UF INT CONSTRAINT UF_FUNCIONARIO_FK FOREIGN KEY (ID_UF) REFERENCES UF,
	 ID_SITUACAO INT CONSTRAINT SITUACAO_FUNCIONARIO_FK FOREIGN KEY (ID_SITUACAO) REFERENCES SITUACAO,
	 ID_SEXO INT CONSTRAINT SEXO_FUNCIONARIO_FK FOREIGN KEY (ID_SEXO) REFERENCES SEXO)
	


CREATE TABLE FORNECEDOR
	(ID_FORNECEDOR INT NOT NULL PRIMARY KEY IDENTITY,
	 RAZAO VARCHAR (50) NOT NULL ,
	 NOME_FANTASIA VARCHAR (50) NOT NULL ,
	 DATA_CADASTRO DATE,
	 CPF_CNPJ_FORNECEDOR VARCHAR (20) NOT NULL ,
	 IE  NUMERIC (20) NOT NULL,
	 END_FORNECEDOR VARCHAR (50) NOT  NULL,
	 END_BAIRRO_FORNECEDOR VARCHAR (50) NOT NULL,
	 END_NUMERO_FORNECEDOR NUMERIC (4) NOT NULL,
	 END_CIDADE_FORNECEDOR VARCHAR (30) NOT NULL,
	 END_CEP_FORNECEDOR VARCHAR (15) NOT NULL,
	 ID_UF INT CONSTRAINT UF_FORNECEDOR_FK FOREIGN KEY (ID_UF) REFERENCES UF,
	 ID_SITUACAO INT CONSTRAINT SITUACAO_FORECEDOR_FK FOREIGN KEY (ID_SITUACAO) REFERENCES SITUACAO,
	 TELEFONE_FORNECEDOR VARCHAR (15),
	 CELULAR_FORNECEDOR VARCHAR (15),
	 EMAIL_FORNECEDOR VARCHAR (30))
	 


CREATE TABLE PET
	(ID_PET INT NOT NULL PRIMARY KEY IDENTITY,
	 NM_PET VARCHAR (10) NOT NULL,
	 ID_ESPECIE INT NOT NULL CONSTRAINT PET_ESPECIE_FK FOREIGN KEY (ID_ESPECIE) REFERENCES PORTE,
	 ID_PORTE INT NOT NULL CONSTRAINT PET_PORTE_FK FOREIGN KEY(ID_PORTE) REFERENCES PORTE,
	 ID_RACA INT NOT NULL CONSTRAINT PET_RACA_FK FOREIGN KEY(ID_RACA) REFERENCES RACA ,
	 ID_CLIENTE INT NOT NULL CONSTRAINT PET_CLIENTE_FK FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE);

CREATE TABLE PRODUTO 
	(ID_PRODUTO INT NOT NULL PRIMARY KEY IDENTITY,
	 CD_BARRAS_PRODUTO INT,
	 DT_CADASTRO_PRODUTO DATE,
	 NM_PRODUTO VARCHAR (20),
	 VL_UNITARIO_PRODUTO_VENDA FLOAT ,
	 VALOR_COMPRA_PRODUTO FLOAT,
	 LUCRO_PORCENTO_PRODUTO NUMERIC (4),
	 QT_PRODUTO INT  ,
	 ID_UNIDADE_MEDIDA INT CONSTRAINT UNIDADE_MEDIDA_PRODUTO_FK FOREIGN KEY(ID_UNIDADE_MEDIDA) REFERENCES UNIDADE_MEDIDA,
	 ID_CATEGORIA_PRODUTO INT CONSTRAINT PRODUTO_CATEGORIA_PRODUTO_FK FOREIGN KEY(ID_CATEGORIA_PRODUTO) REFERENCES CATEGORIA_PRODUTO,
	 ID_FORMA_COMPRA INT CONSTRAINT FORMA_COMPRA_PRODUTO_FK FOREIGN KEY(ID_UNIDADE_MEDIDA) REFERENCES UNIDADE_MEDIDA,
	 NCM_PRODUTO INT,
	 CST_PRODUTO INT,
	 ICMS_PRODUTO INT,
	 ID_FORNECEDOR INT CONSTRAINT PRODUTO_FORNECEDOR_FK FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR,	 
	 ID_TIPO INT CONSTRAINT PRODUTO_TIPO_PRODUTO_FK FOREIGN KEY(ID_TIPO) REFERENCES TIPO_PRODUTO)


CREATE TABLE VENDA 
	(ID_VENDA INT NOT NULL PRIMARY KEY IDENTITY,
	 ID_FUNCIONARIO INT NOT NULL CONSTRAINT VENDA_FUNCIONARIO_FK FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO,
	 ID_CLIENTE INT NOT NULL CONSTRAINT VENDA_CLIENTE_FK FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE,
	 ID_PRODUTO INT NOT NULL CONSTRAINT VENDA_PRODUTO_FK FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO,
	 VL_FINAL_PRODUTOs FLOAT NOT NULL,
	 ID_PLANOPAGAMENTO INT  NOT NULL CONSTRAINT VENDA_PLANO_PAGAMENTO_FK FOREIGN KEY (ID_PLANOPAGAMENTO) REFERENCES PLANO_DE_PAGAMENTO,
	 CALCULAR_IMPOSTO FLOAT NOT NULL)


CREATE TABLE VENDA_ITENS
	(ID_PRODUTO INT NOT NULL CONSTRAINT VENDA_ITENS_PRODUTO_FK FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO,
	 ID_VENDA INT NOT NULL CONSTRAINT VENDA_ITENS_VENDA_FK FOREIGN KEY (ID_VENDA) REFERENCES VENDA,
	 VALOR_VENDA FLOAT NOT NULL,
	 QT_PRODUTO INT NOT NULL)

CREATE TABLE AGENDAMENTO
(ID_AGENDAMENTO INT NOT NULL PRIMARY KEY IDENTITY,
 ID_CLIENTE INT  CONSTRAINT CLIENTE_AGENDAMENTO_FK FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE,
 ID_PET INT  CONSTRAINT PET_ANGENDAMENTO_FK FOREIGN KEY (ID_PET) REFERENCES PET,
 DT_AGENDAMENTO DATE,
 HORA_AGENDAMENTO TIME,
 ID_PRODUTO INT  CONSTRAINT SERVICO_AGENDAMENTO_FK FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO,
 OBS_AGENDAMENTO VARCHAR(250)) 




------------------------------------------INSERT------------------------------------------------------
INSERT INTO SITUACAO
VALUES ('ATIVO'),
		('INATIVO')
		
INSERT INTO TIPO_PRODUTO
	VALUES('PRODUTO'),
			('SERVICOS')

INSERT INTO CATEGORIA_PRODUTO
	VALUES('HIGIENE'),
		  ('RACAO'),
		  ('BANHO'),
		  ('TOSA')

INSERT INTO ESPECIE 
	VALUES ('CACHORRO'),
		   ('GATO'),
		   ('COELHO'),
		   ('HAMSTER')

INSERT INTO RACA(DS_RACA,ID_ESPECIE) 
	VALUES ('GOLDEN',1),
		   ('PITBULL',1),
		   ('VIRA-LATA',1)

INSERT  INTO PORTE 
	VALUES ('PEQUENO'),
			('MEDIO'),
			('GRANDE')

INSERT INTO SEXO
	 VALUES ('MASCULINO'),				 
			('FEMININO')

INSERT INTO FORMA_DE_PAGAMENTO 
		VALUES ('DINHEIRO'),
				('CHEQUE'),
			('CARTÃO DE DEBITO'),
			('CARTÃO DE CREDITO'),
				('PAYPALL'),
				('BITCOIN')
				
INSERT INTO USUARIO(NM_USUARIO,DS_USUARIO,SENHA_USUARIO)
		VALUES ('HUGO','GERENTE','1234'),
				('LIVE','GERENTE','TESTE')

INSERT INTO CLIENTE (DATA_CADASTRO,PESSOA,NM_CLIENTE,CPF_CLIENTE,DT_NASCIMENTO_CLIENTE,ENDERECO_CLIENTE,
            NUMERO_ENDERECO_CLIENTE,BAIRRO_ENDERECO_CLIENTE,CEP_ENDERECO_CLIENTE,ID_UF,ID_SITUACAO,ID_CIDADE)
VALUES('2012-12-12','FISICA','TIAGO LUIGI','1231654','1999-02-22','RUAS DAS ESTRELAS',123,'VILA MARIA','12346',1,1,1)

INSERT INTO PET(NM_PET,ID_ESPECIE,ID_PORTE,ID_RACA,ID_CLIENTE)
VALUES('JOSE HUGO',1,1,1,4)


INSERT INTO CIDADE(DS_CIDADE,ID_UF)
VALUES('SAO PAULO',1)				 

INSERT INTO PLANO_DE_PAGAMENTO (DS_PLANOPAGAMENTO,VL_MINIMO,QT_PARCELAS,ID_FORMAPAGAMENTO)
				VALUES ('CARTAO DE DEBITO','50.00',2,1),
				('CARTAO DE CREDEITO','50.00',2,1)

INSERT INTO UF (DS_UF)
VALUES		('AC'),
			('AL'),
			('AP'),
			('AM'),
			('BA'),
			('CE'),
			('DF'),
			('ES'),
			('GO'),
			('MA'),
			('MT'),
			('MS'),
			('MG'),
			('PA'),
			('PB'),
			('PR'),
			('PE'),
			('PI'),
			('RJ'),
			('RN'),
			('RS'),
			('RO'),
			('RR'),
			('SC'),
			('SP'),
			('SE'),
			('TO')

INSERT INTO FUNCIONARIO(NM_FUNCIONARIO,CPF_FUNCIONARIO,END_FUNCIONARIO,TEL_FUNCIONARIO,EMAIL_FUNCIONARIO,CM_FUNCIONARIO)
		VALUES ('HUGO SOARES BARROS',12345678912,'RUA DAS ESTRELAS',11981564536,'GERENTE','JSCC@GMAIL.COM',5)

INSERT INTO PET(NM_PET,ID_PORTE,ID_RACA,ID_CLIENTE,ID_ESPECIE)
	VALUES ('PET',3,1,3,1)

INSERT INTO FORNECEDOR(RAZAO,CPF_CNPJ_FORNECEDOR,IE,END_FORNECEDOR,END_BAIRRO_FORNECEDOR,END_NUMERO_FORNECEDOR,END_CIDADE_FORNECEDOR,UF_FORNECEDOR)
	VALUES('TESTE', 12345678978, 1121478952, 'RUA TESTE', 'BAIRRO', 421, 'SAO PAULO','SP')

INSERT INTO PRODUTO(NM_PRODUTO,VL_UNITARIO_PRODUTO_VENDA,QT_PRODUTO,ID_FORNECEDOR,ID_TIPO)
	VALUES('SHAMPOO','100.00',2,1,1)



INSERT INTO VENDA_ITENS (ID_PRODUTO,QT_PRODUTO,ID_VENDA)
	VALUES(1,3,9)


GO
INSERT INTO UNIDADE_MEDIDA (DS_UNIDADE_MEDIDA)
		VALUES ('KG'),
				('CX'),
				('UN'),
				('KIT')

INSERT INTO TIPO_PRODUTO
		VALUES ('PRODUTO'),
				('SERVIÇO')

	 INSERT INTO PRODUTO
	 VALUES (123456),
			('2018-05-01'),
			('SABONETE'),
			('15.0'),
			('10.0'),
			('2.0'),
			(15),
			('1'),
			('1'),
			('1'),
			('123'),
			('123'),
			('123'),
			(1),
			(1),
			(2)


------------------------------------------SELECT------------------------------------------------------
SELECT * FROM TIPO_PRODUTO;

SELECT * FROM RACA;

SELECT * FROM PORTE;

SELECT * FROM UF;

SELECT * FROM CIDADE;

SELECT * FROM CLIENTE;

SELECT * FROM  FUNCIONARIO;

SELECT * FROM FORNECEDOR;

SELECT * FROM PET;

SELECT * FROM CATEGORIA_PRODUTO;

SELECT * FROM UNIDADE_MEDIDA;

SELECT * FROM PRODUTO;

SELECT * FROM VENDA;

SELECT * FROM TIPO_PRODUTO

SELECT * FROM AGENDAMENTO

------------------------------------------VIEW--------------------------------------------------------

CREATE VIEW VW_PETS
AS
SELECT 
       P.ID_PET [CODIGO],
       P.NM_PET [NOME],
	   LTRIM(STR(P.ID_ESPECIE)) + ' - ' + E.DS_ESPECIE [ESPECIE],
	   LTRIM(STR(P.ID_RACA)) + ' - '+ D.DS_RACA [RACA],
	   LTRIM(STR(P.ID_PORTE)) + ' - '+ O.DS_PORTE [PORTE],
	   P.ID_CLIENTE
FROM PET P
INNER JOIN ESPECIE E ON E.ID_ESPECIE = P.ID_ESPECIE
INNER JOIN RACA D ON D.ID_RACA = P.ID_RACA
INNER JOIN PORTE O ON O.ID_PORTE = P.ID_PORTE



 CREATE PROCEDURE USP_USUARIOS_SEL
	@LOGIN VARCHAR(50),
	@SENHA VARCHAR(100)
	AS
	SELECT ID_USUARIO, NM_USUARIO, SENHA_USUARIO
	FROM USUARIO
	WHERE NM_USUARIO = @LOGIN AND SENHA_USUARIO = @SENHA


