GO
USE master

GO
DROP DATABASE PETS201802


GO
CREATE DATABASE PETS201802

GO
USE PETS201802;

CREATE TABLE TIPO_PESSOA
	(ID_PESSOA INT NOT NULL PRIMARY KEY IDENTITY,
	 DS_PESSOA VARCHAR(10) NOT NULL)

GO
CREATE TABLE SITUACAO
(ID_SITUACAO INT NOT NULL IDENTITY PRIMARY KEY,
 DS_SITUACAO VARCHAR (10) );
 
GO
CREATE TABLE ESPECIE
	(ID_ESPECIE INT NOT NULL PRIMARY KEY IDENTITY,
	 DS_ESPECIE VARCHAR (50) NOT NULL)

CREATE TABLE PORTE
	(ID_PORTE INT NOT NULL PRIMARY KEY IDENTITY,
	 DS_PORTE VARCHAR (50) NOT NULL)


CREATE TABLE SEXO
	(ID_SEXO INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	 DS_SEXO VARCHAR (10) NOT NULL)

CREATE TABLE TIPO_PRODUTO
(ID_TIPO INT NOT NULL PRIMARY KEY IDENTITY,
 DS_TIPO VARCHAR (30))



CREATE TABLE FORMA_DE_PAGAMENTO
	(ID_FORMAPAGAMENTO INT NOT NULL IDENTITY PRIMARY KEY,
	 DS_FORMAPAGAMENTO VARCHAR (20) NOT NULL)

GO
CREATE TABLE UNIDADE_MEDIDA
(ID_UNIDADE_MEDIDA INT PRIMARY KEY IDENTITY NOT NULL,
 DS_UNIDADE_MEDIDA VARCHAR (5) NOT NULL)



GO
CREATE TABLE CATEGORIA_PRODUTO
(ID_CATEGORIA_PRODUTO INT PRIMARY KEY IDENTITY NOT NULL,
 DS_CATEGORIA_PRODUTO VARCHAR(10) NOT NULL)



CREATE TABLE UF
(ID_UF INT NOT NULL PRIMARY KEY IDENTITY,
 DS_UF VARCHAR(2) NOT NULL);

CREATE TABLE RACA
	(ID_RACA INT NOT NULL PRIMARY KEY IDENTITY,
	 DS_RACA VARCHAR (50) NOT NULL,
	 ID_ESPECIE INT  CONSTRAINT ESPECIE_ANIMAL_FK FOREIGN KEY (ID_ESPECIE) REFERENCES ESPECIE)

/*CREATE TABLE PLANO_DE_PAGAMENTO
	(ID_PLANOPAGAMENTO INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	 DS_PLANOPAGAMENTO VARCHAR (20) NOT NULL ,
	 VL_MINIMO FLOAT NOT NULL,
	 QT_PARCELAS INT NOT NULL,
	 ID_FORMAPAGAMENTO INT NOT NULL CONSTRAINT PLANO_PAGAMENTO_FORMA_PAGMENTO_FK FOREIGN KEY (ID_FORMAPAGAMENTO) REFERENCES FORMA_DE_PAGAMENTO )*/

CREATE TABLE CIDADE
(ID_CIDADE INT NOT NULL IDENTITY PRIMARY KEY,
 ID_UF INT CONSTRAINT UF_CIADADE_FK FOREIGN KEY (ID_UF) REFERENCES UF,
 DS_CIDADE VARCHAR (50)NOT NULL)

CREATE TABLE CLIENTE 
	(ID_CLIENTE INT NOT NULL IDENTITY PRIMARY KEY,
	 DATA_CADASTRO DATE,	 
	 NM_CLIENTE VARCHAR (35) NOT NULL ,
	 CPF_CLIENTE VARCHAR (15),
	 RG_CLIENTE VARCHAR(15),
	 DT_NASCIMENTO_CLIENTE DATE NOT NULL,
	 ENDERECO_CLIENTE VARCHAR (50),
	 NUMERO_ENDERECO_CLIENTE INT,
	 BAIRRO_ENDERECO_CLIENTE VARCHAR (30),
	 CEP_ENDERECO_CLIENTE VARCHAR (9),
	 CELULAR_CLIENTE VARCHAR (15),	 
	 ID_UF INT CONSTRAINT UF_CLIENTE_FK FOREIGN KEY (ID_UF) REFERENCES UF,
	 ID_SITUACAO INT CONSTRAINT SITUACAO_CLIENTE_FK FOREIGN KEY (ID_SITUACAO) REFERENCES SITUACAO,
	 ID_CIDADE INT CONSTRAINT CIDADE_CLIENTE_FK FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE)


CREATE TABLE FUNCIONARIO
	(ID_FUNCIONARIO INT NOT NULL PRIMARY KEY IDENTITY,
	 NM_FUNCIONARIO VARCHAR (50) NOT NULL,
	 CPF_FUNCIONARIO VARCHAR (20) NOT NULL,
	 RG_FUNCIONARIO VARCHAR(10) NOT NULL,
	 END_FUNCIONARIO VARCHAR (50) NOT NULL,
	 TEL_FUNCIONARIO VARCHAR (15) NOT NULL, 
	 EMAIL_FUNCIONARIO VARCHAR (30) NOT NULL,
	 DT_NASCIMENTO_FUNCIONARIO DATE,
	 BAIRRO_ENDERECO_FUNCIONARIO VARCHAR (25) NOT NULL,
	 NUMERO_ENDERECO_FUNCIONARIO INT,	 
	 SALARIO_BASE_FUNCIONARIO FLOAT,
	 CEP_FUNCIONARIO VARCHAR(10),	 
	 ID_UF INT CONSTRAINT UF_FUNCIONARIO_FK FOREIGN KEY (ID_UF) REFERENCES UF,
	 ID_SITUACAO INT CONSTRAINT SITUACAO_FUNCIONARIO_FK FOREIGN KEY (ID_SITUACAO) REFERENCES SITUACAO,
	 ID_SEXO INT CONSTRAINT SEXO_FUNCIONARIO_FK FOREIGN KEY (ID_SEXO) REFERENCES SEXO,
	 ID_CIDADE INT CONSTRAINT CIDADE_FUNCIONARIO_FK FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE)

	 CREATE TABLE USUARIO
	(ID_USUARIO INT NOT NULL PRIMARY KEY IDENTITY,
	 NM_USUARIO VARCHAR (10) NOT NULL,
	 DS_USUARIO VARCHAR (15),
	 SENHA_USUARIO VARCHAR (50)NOT NULL,
	 ID_FUNCIONARIO INT  CONSTRAINT FUNCIONARIO_FK FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO)


CREATE TABLE FORNECEDOR
	(ID_FORNECEDOR INT NOT NULL PRIMARY KEY IDENTITY,
	 RAZAO VARCHAR (50) NOT NULL ,
	 NOME_FANTASIA VARCHAR (50) NOT NULL ,
	 DATA_CADASTRO DATE,
	 CPF_CNPJ_FORNECEDOR VARCHAR (20) NOT NULL ,
	 IE  NUMERIC (20) NOT NULL,
	 END_FORNECEDOR VARCHAR (50) NOT  NULL,
	 END_BAIRRO_FORNECEDOR VARCHAR (50) NOT NULL,
	 END_NUMERO_FORNECEDOR NUMERIC (4) NOT NULL,
	 END_CEP_FORNECEDOR VARCHAR (15) NOT NULL,
	 TELEFONE_FORNECEDOR VARCHAR (15),
	 CELULAR_FORNECEDOR VARCHAR (15),
	 EMAIL_FORNECEDOR VARCHAR (30),
	 ID_UF INT CONSTRAINT UF_FORNECEDOR_FK FOREIGN KEY (ID_UF) REFERENCES UF,
	 ID_SITUACAO INT CONSTRAINT SITUACAO_FORECEDOR_FK FOREIGN KEY (ID_SITUACAO) REFERENCES SITUACAO,
	 ID_CIDADE INT CONSTRAINT CIDADE_FORNECEDOR_FK FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE,
	 ID_TIPO_PESSOA INT CONSTRAINT TIPO_FORNECEDOR_FK FOREIGN KEY (ID_TIPO_PESSOA) REFERENCES TIPO_PESSOA)
	 
CREATE TABLE PET
	(ID_PET INT NOT NULL PRIMARY KEY IDENTITY,
	 NM_PET VARCHAR (10) NOT NULL,
	 ID_ESPECIE INT NOT NULL CONSTRAINT PET_ESPECIE_FK FOREIGN KEY (ID_ESPECIE) REFERENCES PORTE,
	 ID_PORTE INT NOT NULL CONSTRAINT PET_PORTE_FK FOREIGN KEY(ID_PORTE) REFERENCES PORTE,
	 ID_RACA INT NOT NULL CONSTRAINT PET_RACA_FK FOREIGN KEY(ID_RACA) REFERENCES RACA ,
	 ID_CLIENTE INT NOT NULL CONSTRAINT PET_CLIENTE_FK FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE);

CREATE TABLE PRODUTO 
	(ID_PRODUTO INT NOT NULL PRIMARY KEY IDENTITY,
	 CD_BARRAS_PRODUTO INT,
	 DT_CADASTRO_PRODUTO DATE,
	 NM_PRODUTO VARCHAR (20),
	 VL_UNITARIO_PRODUTO_VENDA FLOAT,
	 VALOR_COMPRA_PRODUTO FLOAT,
	 LUCRO_PORCENTO_PRODUTO INT,
	 QT_PRODUTO INT  ,
	 ID_UNIDADE_MEDIDA INT CONSTRAINT UNIDADE_MEDIDA_PRODUTO_FK FOREIGN KEY(ID_UNIDADE_MEDIDA) REFERENCES UNIDADE_MEDIDA,
	 ID_CATEGORIA_PRODUTO INT CONSTRAINT PRODUTO_CATEGORIA_PRODUTO_FK FOREIGN KEY(ID_CATEGORIA_PRODUTO) REFERENCES CATEGORIA_PRODUTO,
	 ID_FORMA_COMPRA INT CONSTRAINT FORMA_COMPRA_PRODUTO_FK FOREIGN KEY(ID_UNIDADE_MEDIDA) REFERENCES UNIDADE_MEDIDA,
	 ID_FORNECEDOR INT CONSTRAINT PRODUTO_FORNECEDOR_FK FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR,	 
	 ID_TIPO INT CONSTRAINT PRODUTO_TIPO_PRODUTO_FK FOREIGN KEY(ID_TIPO) REFERENCES TIPO_PRODUTO)


CREATE TABLE VENDA 
	(ID_VENDA INT NOT NULL PRIMARY KEY IDENTITY,
	 ID_FUNCIONARIO INT NOT NULL CONSTRAINT VENDA_FUNCIONARIO_FK FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO,
	 ID_CLIENTE INT NOT NULL CONSTRAINT VENDA_CLIENTE_FK FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE,
	 VL_FINAL_PRODUTOs FLOAT NOT NULL,
	 ID_FORMAPAGAMENTO INT  NOT NULL CONSTRAINT VENDA_FORMA_PAGAMENTO_FK FOREIGN KEY (ID_FORMAPAGAMENTO) REFERENCES FORMA_DE_PAGAMENTO)


CREATE TABLE VENDA_ITENS
	(ID_VENDA_ITENS INT NOT NULL PRIMARY KEY IDENTITY,
	 ID_PRODUTO INT NOT NULL CONSTRAINT VENDA_ITENS_PRODUTO_FK FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO,
	 ID_VENDA INT NOT NULL CONSTRAINT VENDA_ITENS_VENDA_FK FOREIGN KEY (ID_VENDA) REFERENCES VENDA,
	 VALOR_PRODUTO FLOAT NOT NULL,
	 QT_PRODUTO INT NOT NULL,
	 VALOR_TOTAL FLOAT NOT NULL)

CREATE TABLE AGENDAMENTO
(ID_AGENDAMENTO INT NOT NULL PRIMARY KEY IDENTITY,
 ID_CLIENTE INT  CONSTRAINT CLIENTE_AGENDAMENTO_FK FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE,
 ID_PET INT  CONSTRAINT PET_ANGENDAMENTO_FK FOREIGN KEY (ID_PET) REFERENCES PET,
 DT_AGENDAMENTO DATE,
 HORA_AGENDAMENTO TIME,
 ID_PRODUTO INT  CONSTRAINT SERVICO_AGENDAMENTO_FK FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO,
 OBS_AGENDAMENTO VARCHAR(250))	
 
/*---------------------------------------INSERT---------------------------------------------------------------*/

INSERT INTO TIPO_PESSOA(DS_PESSOA)
	VALUES ('FISICA'),
		   ('JURIDICA')


INSERT INTO UNIDADE_MEDIDA (DS_UNIDADE_MEDIDA)
		VALUES ('KG'),
				('CX'),
				('UN'),
				('KIT')


INSERT INTO SITUACAO
VALUES ('ATIVO'),
		('INATIVO')
		
INSERT INTO TIPO_PRODUTO
	VALUES('PRODUTO'),
			('SERVICOS')

INSERT INTO CATEGORIA_PRODUTO
	VALUES('HIGIENE'),
		  ('RACAO'),
		  ('BANHO'),
		  ('TOSA')

INSERT INTO ESPECIE 
	VALUES ('CACHORRO'),
		   ('GATO'),
		   ('COELHO'),
		   ('HAMSTER')

INSERT INTO RACA(DS_RACA,ID_ESPECIE) 
	VALUES ('GOLDEN',1),
		   ('PITBULL',1),
		   ('VIRA-LATA',1)



INSERT  INTO PORTE 
	VALUES ('PEQUENO'),
			('MEDIO'),
			('GRANDE')

INSERT INTO SEXO
	 VALUES ('MASCULINO'),				 
			('FEMININO')

INSERT INTO FORMA_DE_PAGAMENTO 
		VALUES ('DINHEIRO'),
				('CHEQUE'),
			('CARTÃO DE DEBITO'),
			('CARTÃO DE CREDITO'),
				('PAYPALL'),
				('BITCOIN')

INSERT INTO UF (DS_UF)
VALUES		('AC'),
			('AL'),
			('AP'),
			('AM'),
			('BA'),
			('CE'),
			('DF'),
			('ES'),
			('GO'),
			('MA'),
			('MT'),
			('MS'),
			('MG'),
			('PA'),
			('PB'),
			('PR'),
			('PE'),
			('PI'),
			('RJ'),
			('RN'),
			('RS'),
			('RO'),
			('RR'),
			('SC'),
			('SP'),
			('SE'),
			('TO')



/*---------------------------------------------------------------------------------*/

CREATE PROCEDURE USP_USUARIOS_SEL
@LOGIN VARCHAR(50),
@SENHA VARCHAR(100)
AS
	SELECT ID_USUARIO, NM_USUARIO, SENHA_USUARIO, DS_USUARIO
	FROM USUARIO
	WHERE NM_USUARIO = @LOGIN AND SENHA_USUARIO = @SENHA


CREATE VIEW VW_PETS
AS
SELECT 
       P.ID_PET [CODIGO],
       P.NM_PET [NOME],
	   LTRIM(STR(P.ID_ESPECIE)) + ' - ' + E.DS_ESPECIE [ESPECIE],
	   LTRIM(STR(P.ID_RACA)) + ' - '+ D.DS_RACA [RACA],
	   LTRIM(STR(P.ID_PORTE)) + ' - '+ O.DS_PORTE [PORTE],
	   P.ID_CLIENTE
FROM PET P
INNER JOIN ESPECIE E ON E.ID_ESPECIE = P.ID_ESPECIE
INNER JOIN RACA D ON D.ID_RACA = P.ID_RACA
INNER JOIN PORTE O ON O.ID_PORTE = P.ID_PORTE



CREATE PROCEDURE USP_SEL_RELATORIO_VENDAS
AS
SELECT a.NR_QUANTIDADE, a.NR_VALOR, a.NR_VALOR_TOTAL_ITEM,
b.DT_VENDA,d.DE_NOME, d.DE_DESCRICAO, 
b.ID_VENDA, c.ID_CLIENTE, d.ID_PRODUTO
FROM TB_VENDAS_ITENS a
INNER JOIN TB_VENDAS b ON a.ID_VENDA = b.ID_VENDA
INNER JOIN TB_CLIENTE c ON b.ID_CLIENTE = c.ID_CLIENTE
INNER JOIN TB_PRODUTO d ON a.ID_PRODUTO = d.ID_PRODUTO


CREATE PROCEDURE USP_TB_PET_OBTER_POR_PESSOA
@ID_CLIENTE INT
AS
SELECT ID_PET, ID_CLIENTE, NM_PET
FROM PET where ID_CLIENTE= @ID_CLIENTE

exec USP_TB_PET_OBTER_POR_PESSOA @ID_CLIENTE = 2



