USE [LIVECOMMERCE]
GO

/****** Object:  Table [dbo].[LPARAM]    Script Date: 30/03/2020 14:30:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LPARAM](
	[LMNPARAM] [varchar](10) NULL,
	[LVRPARAM] [varchar](10) NULL
) ON [PRIMARY]
GO


INSERT INTO LPARAM(LMNPARAM)
VALUES ('IMPVND')