CREATE TRIGGER TG_LANCAR_PARCELA  
ON VENDA  
AFTER INSERT  
AS   
BEGIN  
 DECLARE   
 @ID_V INT,  
 @PARCELA INT,  
 @VALOR_P DECIMAL(10,2),  
 @PARC INT =0,  
 @DATAVENC DATE,  
 @ID_CLI int  
   
 SELECT @VALOR_P = VALORPARCELAS, @PARCELA = QTDPARCELAS, @ID_V = ID_VENDA,@DATAVENC = DATAPRIMEIROVENC, @ID_CLI = ID_CLIENTE FROM INSERTED  
 WHILE @PARCELA > 0  
 BEGIN  
  SET @PARC = @PARC+1  
  
  --Lançando a Parcela  
  INSERT INTO PARCELA(PANRPARC,PAVLR,PAIDVEND,PADTVENC) VALUES(@PARC,@VALOR_P,@ID_V,@DATAVENC)  
  
  --Lançando a Conta  
  INSERT INTO CNTPGRC(CTPCONT,CDTLANC,CCODORI,CVLRCNT,CDTVCTO,COBS,CSTATUS,CSNRDOC,CSNRPARC) VALUES(2,GETDATE(),@ID_CLI,@VALOR_P,@DATAVENC,'Conta Lançada a partir da venda','A',@ID_V,@PARC)  
  
  SET @DATAVENC = DATEADD(MONTH,1,@DATAVENC)  
  
  IF((SELECT MAX(PANRPARC) FROM PARCELA WHERE PAIDVEND = @ID_V ) < @PARCELA)  
    CONTINUE  
  ELSE  
    BREAK  
 END  
END