
CREATE PROCEDURE USP_STATUS_VENDA
@ID INT
AS
BEGIN
	UPDATE VENDA
	SET STATUS = 'CANCELADA'
	WHERE ID_VENDA = @ID
	
	DELETE FROM VENDA_ITENS WHERE ID_VENDA = @ID

	EXEC LV_CANCELAR_CONTA_VENDA @ID

END

CREATE PROCEDURE LV_CANCELAR_CONTA_VENDA
@ID VARCHAR(20)
AS
BEGIN
	UPDATE CNTPGRC SET CDTPAG=GETDATE(), CSTATUS='C' WHERE CSNRDOC=@ID
END