CREATE PROCEDURE LV_CONTAPAGAR_RECEBER_TIPO_V1
@TIPO VARCHAR(10)
AS
BEGIN
	IF @TIPO = 1
	
	SELECT V.CCODCONT [Cód],(SELECT TOP 1 L.LTDSC FROM LTGEN WHERE L.LTCOD=@TIPO) [Tipo],C.NOME_FANTASIA, V.CDTLANC [Data Lançamento],
	v.CVLRCNT [Valor], v.CDTVCTO [Venciemnto],v.CDTPAG [Data do Pagamento], v.COBS [Observação]
	FROM CNTPGRC V 
	INNER JOIN FORNECEDOR C ON C.ID_FORNECEDOR = V.CCODORI
	INNER JOIN LTGEN L ON L.LTCOD = V.CTPCONT
	WHERE CTPCONT =@TIPO AND L.LTTP =1
	ELSE
	SELECT V.CCODCONT [Cód],(SELECT TOP 1 L.LTDSC FROM LTGEN WHERE L.LTCOD=@TIPO) [Tipo],C.NM_CLIENTE, V.CDTLANC [Data Lançamento],
	v.CVLRCNT [Valor], v.CDTVCTO [Venciemnto],v.CDTPAG [Data do Pagamento], v.COBS [Observação]
	FROM CNTPGRC V 
	INNER JOIN CLIENTE C ON C.ID_CLIENTE = V.CCODORI
	INNER JOIN LTGEN L ON L.LTCOD = V.CTPCONT
	WHERE CTPCONT =@TIPO AND L.LTTP =1
END