GO
CREATE TABLE TB_BACKUP
(
	BAC_INT_ID INT IDENTITY PRIMARY KEY,
	BC_DT_DATA DATETIME,
	BC_STR_DATABASE VARCHAR(30),
	BAC_STR_DIRETORIO VARCHAR(255),
	BAC_STR_STATUS CHAR(1),
	USU_INT_ID INT
)

ALTER TABLE TB_BACKUP ADD  CONSTRAINT FK_FUNCIONARIO_BACKUP FOREIGN KEY (USU_INT_ID) REFERENCES USUARIO (ID_USUARIO);


/*
PROCEDURE PARA INSERIR DADOS DA GERAÇÃO DE BACKUP

autor: José Hugo Soares de Barros
Data: 23/09/2020

Manutenção:


*/
GO
CREATE PROCEDURE USP_INSERT_LOG_BACKUP
@DATA DATETIME,
@DATABASE VARCHAR(30),
@DIRETORIO VARCHAR(255),
@TATUS CHAR(1),
@USUARIO INT
AS
BEGIN
INSERT INTO TB_BACKUP VALUES (@DATA,@DATABASE,@DIRETORIO,@TATUS,@USUARIO)
END


/*
PROCEDURE PARA LISTAR OS ULTIMOS 20 BACKUPS EXECUTADOS

autor: José Hugo Soares de Barros
Data: 23/09/2020

Manutenção:


*/
GO
CREATE PROCEDURE USP_LISTAR_BACKUP
AS
BEGIN
SELECT TOP 20 U.DS_USUARIO AS [USUARIO],B.BC_DT_DATA AS [DATA],B.BC_STR_DATABASE AS [BASE],B.BAC_STR_DIRETORIO AS [DIRETORIO],
CASE WHEN B.BAC_STR_STATUS = 'F' THEN 'FINALIZADO' ELSE 'ERRO' END AS [STATUS] FROM TB_BACKUP B
INNER JOIN USUARIO U ON U.ID_USUARIO = B.USU_INT_ID
ORDER BY B.BAC_INT_ID DESC
END

